In [51]:
%load_ext autoreload
%autoreload 2
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:95% !important; }</style>"))
import sys
sys.path.insert(0, '/home/kat/Repos/SALSA/')

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## 1) Take a sample of 1000 from ChEMBL.

In [52]:
ddir = '/home/kat/Repos/SALSA/data/'
df = pd.read_csv(os.path.join(ddir,'chembl_valid_lte_120.csv'))
display(df)

seedy = 666
size = 1000

df_samp = df.sample(size, random_state=seedy)
df_samp = df_samp.reset_index(drop=True)
display(df_samp)

                                                    smiles  len
0                                                      CCO    3
1                                                        C    1
2                                                       CO    2
3                                                     NCCS    4
4                                                     NCCN    4
...                                                    ...  ...
1476101  CC1C2CCC3C4CCC5Cc6nc7c(nc6CC5(C)C4CC(=O)C32COC...  120
1476102  CNC(=O)c1cc(Oc2ccc(Nc3ccc(Cl)c(C(F)(F)F)c3)cc2...   51
1476103  Cc1cc(C)c2c(c1)N(CCCN1CCN(c3ccccc3)CC1)C(=O)c1...   58
1476104  CCC(C)n1ncn(-c2ccc(N3CCN(c4ccc(OC(c5ccc(F)cc5F...   81
1476105  O=C1c2cc(Cl)nnc2Oc2ccc(C(F)(F)F)cc2N1CCCN1CCN(...   59

[1476106 rows x 2 columns]

                                                smiles  len
0                    COc1c(Br)cc2c(c1Br)OC(=O)C2=C(C)C   33
1                   COc1cc(CC(C)(O)Cc2ccccc2F)nc(OC)n1   34
2             C=C(C)CSc1nnc2n(C)c(=O)c3c4c(sc3n12)CCC4   40
3                Cc1ncccc1C(=O)NC1CC(=O)N(CC(F)(F)F)C1   37
4         Cc1ccc(S(=O)(=O)NCc2cccc([N+](=O)[O-])c2)cc1   44
..                                                 ...  ...
995  CCC1SC2=NC(C)=C(C(=O)OCCOC)C(C=Cc3ccccc3OC)N2C1=O   49
996               OC(CNCc1ccc(F)cc1)COc1cccc2[nH]ccc12   36
997  O=S(=O)(c1ccccc1)c1ccc(-c2nn(CN3CCOCC3)c(=S)n2...   60
998              Cc1ccc(CNC(=O)NC2CCCN(c3ncccn3)C2)cn1   37
999                Cc1cccnc1CN1CCC(C)(O)C(Oc2ccccc2)C1   35

[1000 rows x 2 columns]

## 2) Calculate all properties.

In [48]:
from tqdm import tqdm
from property_predictors import surface_predictor

all_props = []

for sm in tqdm(df_samp.smiles.values,total=len(df_samp)):
    props = surface_predictor(sm)
    all_props.append(props)

100%|██████████| 1000/1000 [00:02<00:00, 477.55it/s]

## 3) Get Mahalanobis distance. (per mol)

In [49]:
import numpy as np
from scipy.spatial import distance

df_samp['mahalanobis'] = -1

props_arr = np.vstack([np.array(x) for x in all_props])
print(props_arr.shape)

# Get rid of all-zero properties (to ensure det!=0)
to_keep = []
for i in range(props_arr.shape[1]):
    s = sum(props_arr[:,i])
    if s==0:
        continue
    else:
        to_keep.append(i)

props_arr_clean = props_arr[:,to_keep]
print(props_arr_clean.shape)

(1000, 49)
(1000, 47)

In [50]:
dists = []

for i,row in df_samp.iterrows():
    
    samp_arr = np.expand_dims(props_arr_clean[i],axis=0)    
    
    d = distance.cdist(samp_arr, props_arr_clean, 'mahalanobis')
    dists.append(d)
    
    print(len(d[0]),d)
    break

1000 [[ 0.          8.43397538  8.97466726  8.02676529  8.68656343 11.1331645
   8.23384394  8.53574656 10.03382568 10.34025052  8.75111246  6.58281462
   8.41165117  9.568522    7.4355145   6.09712094  6.95625478  8.10794294
   8.50215669  8.79561774  8.0017659   7.82813554  8.96861136  8.7965605
   7.63629923  8.28968225  9.23663311  8.23056334  9.82000796  8.65067107
   8.38359106  7.80846345 10.46313534  7.75230228  8.23922687  8.28697881
   9.16071179  8.33867009  7.45308934 13.96109807  9.76023777  8.7491159
   9.51867479  9.154405    8.10277378  8.24099893  8.0567046  15.86818077
   8.55560337  7.80892334  8.23617558 14.58550313  8.36477323  9.74044648
   9.93006543  8.03478692  8.05826068  8.27563995  9.38210879  8.39602116
   8.77738823  8.4795686  10.14218299  8.60360793  8.66086511  9.69780164
   8.22388562  8.96232157  9.58184546  8.19382225 12.59781666  7.36484767
   7.4704987   7.86327703  8.4486345   8.79580241  7.20997322 10.50241307
   8.26516492  7.33635074  8.17635319  7.8561962   6.67929486  8.99580572
   5.84802734  8.38695336  7.51310668  8.06971879  7.04099134  7.86591513
  11.34996453  8.44050685  9.67432868  9.56583048  7.6416367   8.30673363
   9.94919021  7.75117316  8.07947471  7.87116976  8.88552121  8.9626842
  10.25179228 10.59827733  7.43524965  9.93667873 10.09511452  9.68723775
   8.81523    10.40900144  8.16121936 10.40258397  5.83458856 10.36729489
  10.23732798  9.16631292 10.71525911 10.76300631  7.39644952  8.87927458
   9.64436203  9.93761113  9.80727055 17.69343939  7.02515016  9.68463306
   9.41579789  8.79080683  9.54535843 10.83913569  7.49214338  9.40236676
  10.55228501  7.52511885  9.36773719  6.59095949  8.99089739  9.29740221
   8.7945108  11.68933699  9.57090029  7.72954417  7.97687798 11.41998731
  12.52780223  7.01825214  7.07421265  6.55320454  8.64943288  7.68340668
   9.88799394 11.4121225   9.43630551  9.03028809 10.13078474 10.26543619
   9.29792564  7.9548762   8.64207239 12.05798456  9.65491497  8.65789244
   7.86295895  6.77029456  9.22120096  7.21548806  8.24936768  8.52805809
   8.19483847  9.40251547  8.29534176  6.63727345  9.2756016   8.46830165
   8.09045953  8.73721339  8.47526819 16.96462004  8.60116038  8.52632989
   9.05891333 11.45437251  7.50951584  8.33455448  9.10489593  7.94972695
   7.59879013  9.35303047  7.59982066  7.91608219  9.76552275 10.17119352
   8.4900333   8.64327525  8.31038432  8.24107806  8.00682287 14.50775596
   7.75528383  7.41149249 10.82045452  6.68333933  7.68705996  9.28176956
   8.82288787  7.92128413  8.94816881  8.5475399  11.55861942  9.79555158
   8.59714098  8.36787617  8.55808894 16.71421494  8.48958407  8.40782038
   9.35508146  9.89466606 10.64035186  7.94162228  6.68445813  7.33039043
   7.83523121  8.98841667  8.32930164 11.6014572   8.05353123  9.36751763
   7.76767456  8.79138046  9.56464355  8.27302317  8.68246515  7.82699216
   8.33359344  8.31187942  9.16167503 10.38510194 10.83487589  7.26760743
   8.47241822  8.2053829   8.58761671  8.58873375  8.41450682  7.87117771
   8.04305458  9.9647269  10.72670668  8.62488045  7.86711836  7.41315581
   9.27008516  7.12361309  7.62672659  9.35101706  9.05751979  7.58678116
  10.75112966 10.44938281 14.90986266  7.82520291 11.10967781  9.4404164
   7.83364354  5.95243705  7.7037149   9.69302772  8.6621041   9.29512255
   8.62598306  8.15946101  9.41603727  7.64951531  9.89055611  7.40792279
   9.1788578   9.53256666  7.95709846  7.54820548  8.33839765  9.59312475
  10.39747242 15.26802362  7.98359064 10.94940243  8.56614064  6.09874444
   9.18567119  9.37273404 12.8353604   6.68507422  8.73186561  8.14323827
   5.8955998   7.9353933   8.46978875  7.97958278  9.75359034 12.933961
   9.33729695 14.54973886  7.49758679 10.03600998  8.23389887 10.40085454
   9.34016741 14.28754202 10.09498641  7.78123762  6.74293577  9.1927495
   8.88640293 12.33887511  8.43396094  9.0562071   8.87496864  7.52743722
  10.96722113 10.01549911 11.57348994 11.04976002 10.23099845 12.33147976
   8.94532456  6.84239079  7.9859143   8.85020777  7.92981047 13.06907861
   9.98625645  9.37527487  8.40285673  7.15730223 11.21010445 10.43413897
   9.38574435  8.72855696  9.48178925  7.72959173  9.90083118  7.80606548
   8.07775539 10.52485232  7.51397655  7.25361671 10.66114957 10.82397479
   6.71403606  8.60237107  7.88940988  8.93640695  9.24053091  8.41527188
  10.54424681  9.79104416  9.53944512  8.47451061  8.44170499  8.01672643
   8.75809875  7.69757518  7.54216482 11.53347866  9.03848584  7.82804016
   8.34033894 11.38125251  8.65387478 11.09378028  8.10060312 10.10796742
   7.71690712 10.71931483  8.36711426  7.31199408  8.28238575  8.33342236
   8.66295456  7.46162906  7.9923692   9.10460983  8.77989816  7.86744237
   9.73602396  8.13073501  8.29358831 10.63569871  8.26117653  8.46027178
   7.78614068  9.47500174  8.8437649   8.88486887  9.42433888 11.95602023
   7.81813592  9.54195084 13.72696513  9.17460994  6.33704141  7.5814702
   8.0530893   8.74028973  8.78317157  7.87518956  7.72250591  8.52393737
   8.31833199  9.5456978   7.89871135  9.57615659  9.32214509  8.74444512
   8.83349219  8.66014556  9.24253656  8.92616939  7.83906978  9.13464092
  11.37337341  8.57429588  9.96269483  8.63194251  7.87357187  9.18726939
  13.67135604 13.02652074  9.19313082  8.39236258  9.04660335  8.57961483
   7.97755573  8.75864906  7.87634569  9.36634057  8.10900741  9.79326538
  11.01679036  9.43084029  7.77793216  8.14114217  8.29002318  8.99300528
   9.30401862  9.87542176  7.84556196  8.46455609  8.34425032  9.07688595
   8.39303756  7.96547576  9.77763828  9.93394778 11.28783976  8.91923181
  17.47933361  8.63553379  8.46563297  9.6314194  18.56986456 11.00087353
   8.07368338  8.86501273  7.64135309  8.49539469 10.90561093  9.54286488
   8.61954895  8.42230994  7.02553575  8.04237715 12.77943973  8.84169575
   8.91965226  7.67248554  8.10381496  8.36437322  8.18637577  8.57644628
   7.25221257  9.32862701  8.10500427  7.70942977  9.82785275 10.08808043
   9.17310968 11.10110149  7.37999322 10.44280854 17.56919051 13.10589214
   9.90218495  7.61779215  8.35400102  8.71139028 10.2629679   8.07891749
   7.77909908 14.53293831  8.03427532  8.59028196 10.04490916 10.61167333
   8.39077132  7.37871665  8.24625962  8.94728727  8.77118044 10.04259399
   8.80232906  8.00061953  9.75981285  7.87215477  7.82954396  7.36317014
   5.85577373  8.60064529  9.59499096  8.4453858   6.47544042  8.77492559
   7.77176622  8.50290795  9.40075421  7.25797614  9.52564841  9.1218334
   9.54781898  7.08548001  8.86348298 10.41999543 11.24148251  7.05389387
   7.51953728  9.2519668   7.49405309  8.20126712  9.4554253   7.99043505
   7.47860574  9.23672179 10.77879966  7.54162523 12.45938655  7.10562306
   6.80953682  7.89465735  8.75233043  7.30740476  7.95783968  9.88290689
   7.77363685  9.35675334  8.67091346  8.87843633  8.75964136  9.96668
   9.29864372  7.53133533  9.22208067  8.99990392  8.79131122  5.99771704
   6.95318587 11.07371833  9.01863195  8.36879967  8.36576444  5.6878695
   8.94858176  8.5452418  10.77832632 10.4756429  10.85828889  7.73823517
   7.97568953  9.31182437  9.53797738  9.01025876  8.96337674 10.99145997
   7.84805062  9.68183034  8.63119862 10.05213164  8.48065056  7.90771164
  10.22333623  8.29919695  8.10239795 11.61465404  9.52411336  8.58435997
   6.30618261  9.64659045  9.00722772  8.51612582  8.57078312  8.87599422
   9.70541031  7.56722365  9.11701772 15.95111985  9.55448597  8.34989031
   8.6627002   7.17595685  9.56899045 10.52902932  9.61118786  8.44481148
   7.18610533  7.5458205   8.79925164  9.73842581 10.51966866  9.38852636
  10.31291798  8.86482946 11.00229472  9.53533588  8.42708631  9.41427195
   8.11219235  9.48722625  8.24588178  8.8315129   7.75321559 10.37497306
  24.63364272 10.24552724  9.39605528  7.59125737  7.83473244  9.76510808
   7.96067695  9.87086875  9.25520261  9.04200063  8.80939381 10.20255777
  10.84309242  8.45478186  9.15161142  8.90703462  9.26386455  9.7515413
   7.44158057  7.49085169 10.73756501  8.77922016 10.31311109  9.83143188
  10.46153809 12.91620224  8.84240697  9.20419031  9.67079603  8.38239908
   9.98942819  8.36913083  9.86263727  7.55062805  8.17372801  7.89440209
   9.73352285  9.5429651   8.81192179  7.59800962  8.71930488 19.4729344
   8.80200762  9.11723138  7.81283881  7.84620466  8.65079913  8.00695754
   7.98629679 10.83483252 10.92933607  8.41552638  7.02297106  8.07116181
  13.44989473  7.64570475  7.8962715   7.88337046  8.54041917  9.1641705
  11.03004642 11.56233553  9.72487511  9.17997022  7.41229417  5.99580832
   8.26144908  7.18069338 10.24320359  9.04023316  7.94836581  9.23447192
   7.960706   11.15805989 12.12036434  9.55705929  9.42870954  7.63604579
   9.25137952  8.17228606  9.55497195 10.46128782 10.60366296 10.27054967
  10.67561993  8.17878356  8.85441476  7.91660994  8.87119476  6.89827083
   9.11365471 11.09993029  7.93460144  6.50226018  8.49079614  8.53395832
   8.3893475   8.85901333 10.09866126  8.48722325 10.01269247  9.55436735
   8.66829377  8.73534921  8.55457252 11.46020988  8.32622319  7.88996498
   9.46382606 11.16449922  8.17278687 13.04103719  8.90549587  9.29445825
   9.19890455  8.16448553  9.81005214  9.21407174  7.46461393 10.66039232
   9.34900319  9.84268141  9.4350179   8.99823341  9.77298887  7.78818395
   7.0286819   8.18167297 11.55940226  8.51476194 10.46605297  8.83722638
   8.66889563  7.12855774 10.14376336 11.0346323   8.75279886  9.62656196
   7.44803575  7.11116837  7.71744374  7.58665309  7.9241654   8.58203117
   9.0116231   9.05069593  9.16262505  7.85115029  6.91036707 10.98793497
   7.95109936  9.38237773  8.60818433  8.05719954  7.16992764  8.97745208
   7.95034855  9.49154645  7.33792719  8.79555499 13.99005749  7.17253405
   8.38753915 10.81460469  8.50973443  9.37206462  9.67972407  9.91566244
   8.59857958  8.40796316  7.01934961  8.76880934  8.76454796  8.08833558
   9.08017456  7.27322738  7.79546257  8.35024834  9.3460068   8.17626729
   8.03322244  7.3870763   9.88106608  7.78621214 13.43214977  9.85763363
   7.74055372  9.31983404  8.38970222  8.86190337  6.83232866  9.34281884
   8.87017199  8.66362107  8.17114657 12.11738324  8.98116638  8.54872063
   8.79087736  9.16244385  9.33205595  7.5970984  10.0872651  14.26218583
   9.49651421  9.36345487  7.48433704  9.63371234  8.86372338  7.77635258
   8.71153933 10.70906232  8.19993459  8.96027751  8.62689756  8.5991258
  10.38174605 11.23637705  6.06412394  8.59758489  8.10317887  8.91371604
   9.76032454  8.15460756 10.09129202  7.96383963  8.94055112 10.43390811
   8.34795392 18.84204187  9.97692475  9.87423982 11.61662463  8.70591583
   8.74413717  8.72765732  9.01399907  7.53677468  7.1064505   8.50084354
  10.26996871  8.35130161  7.6379073   5.70287403  8.1192699  12.05871396
   8.93559154  7.67069654  8.10450235  8.42064901  9.02251125  8.00325149
   8.78650393  9.23198767  7.72442078  8.21299809  8.75480348 13.73190637
   8.93682985  6.08627872  8.15427491  8.160071    9.40627676  9.50354871
   8.74042653  8.8542484  10.60897638  9.02975921  8.08220443  9.3220503
  11.07930403 10.94180122  8.95457601  8.81208549 10.36814013  9.99691471
   9.94951479  8.19770588  9.49560054  7.34143771  9.11981903  9.20675828
   8.75927171  9.93741412  8.5537854  15.54932334  9.4835053   8.53567402
   8.52868839  8.84660487  8.93191406  9.30884139  9.36095991  8.84458905
   9.61993698  8.38932278  8.38546164 10.21915839 10.63611491  9.38843265
  10.54561978  7.34022219  7.92954115  7.77305069  8.84819131  8.11949675
   8.74369342 10.42027998 10.89648936  7.8262795   8.23067558  8.98279538
   7.97510143  8.35296689  8.88551623 11.79813857  8.97692989 11.3212912
   7.70174089  7.50251826  8.87935211 12.19239356 14.94372212  7.84371307
   8.77773843  9.95338255  7.77301824  8.07385142 10.9482855   8.80349555
   8.92978946  7.69271809  9.53048491  9.19807832  7.82217517  7.72170429
  10.25870572  8.53197787  9.64652741 12.37342234  8.21260303  8.46346317
   8.60516077  7.95443655  8.23795084 10.94399463  8.44868803 11.59241808
   9.02841725  8.75326209  7.53414572 11.03079596  8.14194554  7.07270777
  11.65293653  8.5368784   9.3381958  15.96873138  9.32343392  8.98980375
   8.62305353 12.932       9.36219358  7.13968863 10.45420542  7.25951935
   8.01809773 11.92024277  8.90095454  7.71262697]]